# Generated by Django 4.2.7 on 2023-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tlg_bot_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен тлг-бота'),
        ),
        migrations.AddField(
            model_name='user',
            name='tlg_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Чат ID тлг-бота'),
        ),
    ]
