# Generated by Django 4.2.7 on 2023-12-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tlg_bot_token_user_tlg_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tlg_bot_token',
        ),
    ]
