# Generated by Django 4.2.7 on 2023-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего оповещения'),
        ),
    ]
